car_parts#;drop table car_parts;

CREATE TABLE `car_parts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `car_id` int(11) DEFAULT NULL,
  `part_number` text COLLATE utf8_unicode_ci,
  `description` text COLLATE utf8_unicode_ci,
  `ebay_article_number` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ebay_selling_type` int(11) DEFAULT NULL,
  `ebay_online_since` date DEFAULT NULL,
  `ebay_state` int(11) DEFAULT NULL,
  `price` decimal(18,2) DEFAULT NULL,
  `postage_germany` decimal(18,2) DEFAULT NULL,
  `postage_austria` decimal(18,2) DEFAULT NULL,
  `postage_swiss` decimal(18,2) DEFAULT NULL,
  `postage_europe_with_eu` decimal(18,2) DEFAULT NULL,
  `postage_europe_without_eu` decimal(18,2) DEFAULT NULL,
  `postage_world_wide` decimal(18,2) DEFAULT NULL,
  `picture_url1` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `picture_url2` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `picture_url3` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `picture_url4` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `picture_url5` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `picture_url6` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `remark` text COLLATE utf8_unicode_ci,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `quantity` int(11) DEFAULT NULL,
  `stock` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ebay_shop_category` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `second_price` decimal(18,2) DEFAULT NULL,
  `ean` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `show_car_details` int(11) DEFAULT NULL,
  `show_car_overview` int(11) DEFAULT NULL,
  `state` int(11) DEFAULT NULL,
  `postage_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_car_parts_on_car_id` (`car_id`),
  KEY `index_car_parts_on_ebay_article_number` (`ebay_article_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
